from __future__ import annotations
import inspect
import sys
from pathlib import Path
from typing import get_args, get_origin, Union

# Ensure package root is in python path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

import oem_knowledge.models as models
from pydantic import BaseModel


def map_type_to_ts(py_type) -> str:
    origin = get_origin(py_type)
    args = get_args(py_type)

    if origin is list:
        return f"{map_type_to_ts(args[0])}[]"
    elif origin is dict:
        return f"Record<{map_type_to_ts(args[0])}, {map_type_to_ts(args[1])}>"
    elif origin is Union or origin is getattr(Union, "__origin__", None): # support optional
        non_none_args = [a for a in args if a is not type(None)]
        ts_types = [map_type_to_ts(a) for a in non_none_args]
        joined = " | ".join(ts_types)
        if type(None) in args:
            return f"{joined} | null"
        return joined
    elif str(py_type).startswith("typing.Literal") or str(origin).endswith("Literal"):
        return " | ".join(f'"{a}"' for a in args)
    elif py_type is str:
        return "string"
    elif py_type in (int, float):
        return "number"
    elif py_type is bool:
        return "boolean"
    elif inspect.isclass(py_type) and issubclass(py_type, BaseModel):
        return py_type.__name__
    elif py_type is None:
        return "null"
    else:
        return "any"


def generate_ts() -> str:
    classes = [
        models.ConceptRelation,
        models.ConceptData,
        models.KnowledgeEvent,
        models.TodoItem,
        models.RetrievalMetrics,
        models.ContextMetrics,
        models.KnowledgeUsageMetrics,
        models.MetricsSchema,
    ]

    lines = [
        "// ─── AUTOGENERATED TYPES FROM PYDANTIC MODELS ───",
        "// Run generate_ts_types.py to update.",
        "",
    ]

    for cls in classes:
        lines.append(f"export interface {cls.__name__} {{")
        for field_name, field in cls.model_fields.items():
            ts_type = map_type_to_ts(field.annotation)
            # Make optional if field accepts None/null
            origin = get_origin(field.annotation)
            args = get_args(field.annotation)
            is_optional = False
            if origin is Union and type(None) in args:
                is_optional = True
            
            suffix = "?" if is_optional else ""
            lines.append(f"  {field_name}{suffix}: {ts_type};")
        lines.append("}")
        lines.append("")

    return "\n".join(lines)


def main():
    ts_code = generate_ts()
    out_dir = Path(__file__).resolve().parent.parent.parent.parent / "plugins" / "generated"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "schemas.ts"
    out_path.write_text(ts_code, encoding="utf-8")
    print(f"Generated TS schemas to {out_path}")


if __name__ == "__main__":
    main()
